Powering HackIllinois
HackIllinois/blog pull request #50
Opened 2018-08-11 16:28 UTC by ASankaran

Closes #30.

This post is about the HackIllinois API and some the decisions that were made while designing and implementing it.

## Pre-Approval
- [ ] Post properly titled
- [ ] Post contains proper front matter
- [ ] `featured` tag has been added to this post
- [ ] `featured` tag has been removed from other posts
- [ ] Images and assets have been added
- [ ] Post has been tested locally with Jekyll
- [ ] Spelling has been checked

## Pre-Deploy
- [ ] Reviews have been resolved or otherwise addressed
- [ ] Approval from a repo owner
- [ ] Post file name has been updated to current date
- [ ] Post front matter has been updated to current date
- [ ] Merged master

2018-08-11 16:33 UTC, apache8080 commented
I think most of the post is really solid. The individual section on each service may not be necessary for this post. If there were some services that had interesting challenges then we may be able to spin it out into another post.

2018-08-14 14:37 UTC, justinyangusa commented
Great start, @ASankaran! Based on our conversation yesterday, I’ll be looking for the next revision to be shorter with additional details on the microservice architecture decision. Descriptions for each microservice can be moved into documentation for the API.

2018-08-14 16:26 UTC, redsn0w422 requested changes
Good start! Remember to spell check the post 😄 

Also, I'd be more explicit about why we opted to write our own API vs. using something else, or something more simple like Typeform/Google docs/etc.

2018-08-14 16:26 UTC, redsn0w422 commented on _posts/2018-08-11-powering-hackillinois.markdown
> +As mentioned at the begining of the post, there have been a few iterations of the API over the years. The purpose and requirements of the API over the years has remainds relativley constant, however
spellcheck

2019-07-04 16:06 UTC, closed without merging