Call for Mentors
HackIllinois/blog pull request #52
Opened 2018-08-19 19:41 UTC by justinyangusa

Closes #40.

This post is about an open call for mentors to attend HackIllinois 2019. Potential mentors, many of whom are unfamiliar with HackIllinois, can reference this post to learn more about mentorship and HackIllinois itself. Interested contributors are invited to fill out the interest form to be contacted by Outreach. The release of this post is intended to be coordinated with social media announcements and posts on forums such as Hacker News and Reddit.

## Pre-Approval
- [x] Post properly titled
- [x] Post contains proper front matter
- [x] `featured` tag has been added to this post
- [ ] `featured` tag has been removed from other posts
- [ ] Images and assets have been added
- [ ] Post has been tested locally with Jekyll
- [ ] Spelling has been checked

## Pre-Deploy
- [ ] Reviews have been resolved or otherwise addressed
- [ ] Approval from a repo owner
- [ ] Post file name has been updated to current date
- [ ] Post front matter has been updated to current date
- [ ] Merged master

2018-08-19 20:06 UTC, apache8080 commented
@justinyangusa This looks good to me.

2018-08-20 02:26 UTC, redsn0w422 requested changes
Good start. Couple inline comments, as well as more general things.

- I would define what we consider an open source contributor to be, and provide some high-level examples. Mentioning we've had people younger than 20 and college students would help.

- I think we should link to the mentor spotlights somehow, either by just linking if they want to read about someone's experiences, or even pulling some quotes out and scattering it throughout the post.

2018-08-20 02:26 UTC, redsn0w422 commented on _posts/2018-08-21-call-for-mentors-hackillinois-2019.markdown
> +Group sizes vary, but we find that the most successful groups have a ratio of 4-6 students per mentor and have 1-3 mentors that come ready with a handful features and fixes for the students to get st
I would mention that the mentor gets to provide preference for their group size - we want them to be comfortable.

2018-08-20 02:26 UTC, redsn0w422 commented on _posts/2018-08-21-call-for-mentors-hackillinois-2019.markdown
> +Although there is a wide range of skill levels, most students are well-versed with writing code for classes or personal projects, but don't necessarily have familiarity with working in larger codebas
I'd say:

"or open source workflows (like git)."

2018-08-20 02:26 UTC, redsn0w422 commented on _posts/2018-08-21-call-for-mentors-hackillinois-2019.markdown
> +Team members will be able provide details regarding travel and accommodations based on your individual situation following initial conversations.
Which team?

2018-08-20 02:26 UTC, redsn0w422 commented on _posts/2018-08-21-call-for-mentors-hackillinois-2019.markdown
> +We will review submissions, and a team member will reach out to you via email to learn more about your projects and answer any questions you may have. The Mentor Interest Form is a way for you to get
Again, I'd say "staff" or something.

2018-08-20 03:10 UTC, apa-123 commented on _posts/2018-08-21-call-for-mentors-hackillinois-2019.markdown
> +What do I get out of attending HackIllinois?
can add this line here - HackIllinois may subsidize travel/lodging costs on a case-by-case basis.

2018-08-20 03:10 UTC, apa-123 commented on _posts/2018-08-21-call-for-mentors-hackillinois-2019.markdown
> +Feel free to fill out the Mentor Interest Form anyway. We can contact you about other opportunities, such as our fall HackNights or HackIllinois in future years.
potentially provide one more line here about HackNights to give more information

2018-08-20 03:10 UTC, apa-123 commented on _posts/2018-08-21-call-for-mentors-hackillinois-2019.markdown
> +We love questions! Mentors are the core of the HackIllinois experience and we work closely with each mentor. Just shoot us an email at [opensource@hackillinois.org](mailto:opensource@hackillinois.org
echoing the "team" comment from earlier, "staff" here as well

2018-08-21 03:09 UTC, rohinb2 commented on _posts/2018-08-21-call-for-mentors-hackillinois-2019.markdown
> +Mentors lead a group of students in addressing issues on projects that the mentors contribute to. Unlike at other collegiate hackathons, mentors don't just support students in fixing bugs here and th
addressing issues on projects **and** building new open source tools

2018-08-21 03:11 UTC, rohinb2 reviewed
Looks good! Pretty straightforward, seems fine to me.

2018-08-22 15:42 UTC, smg155 approved these changes
Looks pretty good to me!

2018-08-22 22:09 UTC, merged